name: Deploy and Test Branch

on:
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize, reopened]
      branches: develop

jobs:
  getbranch:
    runs-on: ubuntu-latest
    outputs:
      netmakerbranch: ${{ steps.checkbranch.outputs.netmakerbranch }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netmaker
          ref: develop
      - name: check if branch exists
        id: checkbranch
        run: |
          if git show-ref ${{ github.ref_name}}; then
            echo branch exists
            echo "netmakerbranch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo branch does not exist
            echo "netmakerbranch=develop" >> $GITHUB_OUTPUT
          fi
  
  terraform:
    needs: getbranch
    uses: gravitl/devops/.github/workflows/terraform.yml@master
    with:
      netmakerbranch: ${{ github.ref_name }}
      netclientbranch: ${{ needs.getbranch.outputs.netmakerbranch }}
    secrets: inherit


  testbranch:
    needs: [getbranch, terraform]
    uses: gravitl/devops/.github/workflows/branchtest.yml@master
    with:
      tag: ${{ github.ref_name }}
      network: ${{ github.ref_name }}
    secrets: inherit
    
