name: Integration Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: |
         env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .
         env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build .
         env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build .
         env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build .
 
  tests:
    env:
      DATABASE: sqlite
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run tests
        run: |
            go test -p 1 ./... -v
            go install honnef.co/go/tools/cmd/staticcheck@latest
            { ~/go/bin/staticcheck  -tags=ee ./... ; }
        env:
          DATABASE: sqlite
          CLIENT_MODE: "off"
